# 04 - Construct core pre-treatment covariates

This notebook builds the first cell-level covariate table used by later estimation notebooks.

All covariates are aggregated to the same analysis grid used by Notebook 01 for deforestation. The intended production grid is `1km` by `1km`; if only legacy `0p080` files are present, the notebook can run in development mode but prints that clearly.

The central rule is that every covariate must be frozen before treatment exposure. For time-varying covariates, treated cells use only years strictly before their first treatment year. Never-treated cells use a common baseline window. Static geography covariates are time-invariant by construction.

Expected outputs:

- `data/intermediate/panel_core_covariates.parquet`
- `outputs/tables/04_covariate_balance_summary.csv`
- `outputs/tables/04_covariate_source_catalog.csv`

## Environment snapshot

In [1]:
from pathlib import Path
import json
import os
import re

import numpy as np
import pandas as pd
import geopandas as gpd

pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 160)

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

CONFIG_PATH = PROJECT_ROOT / "configs" / "project_config.json"
PROJECT_CONFIG = json.loads(CONFIG_PATH.read_text()) if CONFIG_PATH.exists() else {}

RAW_DIR = Path(PROJECT_CONFIG.get("data_dirs", {}).get("raw", PROJECT_ROOT / "data" / "raw"))
INTERMEDIATE_DIR = Path(PROJECT_CONFIG.get("data_dirs", {}).get("intermediate", PROJECT_ROOT / "data" / "intermediate"))
PROCESSED_DIR = Path(PROJECT_CONFIG.get("data_dirs", {}).get("processed", PROJECT_ROOT / "data" / "processed"))
TABLE_DIR = Path(PROJECT_CONFIG.get("output_dirs", {}).get("tables", PROJECT_ROOT / "outputs" / "tables"))
FIGURE_DIR = Path(PROJECT_CONFIG.get("output_dirs", {}).get("figures", PROJECT_ROOT / "outputs" / "figures"))

for path in [RAW_DIR, INTERMEDIATE_DIR, PROCESSED_DIR, TABLE_DIR, FIGURE_DIR]:
    path.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Intermediate dir:", INTERMEDIATE_DIR)
print("Tables dir:", TABLE_DIR)

Project root: c:\Users\cpedr\OneDrive - Hertie School\PhD\Paper 2\paper2
Intermediate dir: C:\Users\cpedr\OneDrive - Hertie School\PhD\Paper 2\paper2\data\intermediate
Tables dir: C:\Users\cpedr\OneDrive - Hertie School\PhD\Paper 2\paper2\outputs\tables

## User configuration

The `FREEZE_END_YEAR_NEVER_TREATED` setting is the common baseline cutoff for never-treated cells. Treated cells always use observations with `year < first_treat_year`. Static covariates ignore this year rule because their source is time-invariant or fixed at baseline.

In [2]:
# --- Upstream inputs ---
# Production target: same 1km x 1km grid used for the deforestation panel in Notebook 01.
INTENDED_GRID_TAG = "1km"
ALLOW_LEGACY_GRID_FALLBACK = True
LEGACY_GRID_TAGS = ["0p080", ""]


def tagged_path(stem, suffix, tag):
    if tag:
        return INTERMEDIATE_DIR / f"{stem}_{tag}{suffix}"
    return INTERMEDIATE_DIR / f"{stem}{suffix}"


def resolve_grid_artifacts(target_tag=INTENDED_GRID_TAG):
    candidates = [target_tag]
    if ALLOW_LEGACY_GRID_FALLBACK:
        candidates += [tag for tag in LEGACY_GRID_TAGS if tag not in candidates]
    for tag in candidates:
        panel_path = tagged_path("panel_treatment", ".parquet", tag)
        grid_path = tagged_path("grid_geometry", ".geojson", tag)
        if panel_path.exists() and grid_path.exists():
            return tag, panel_path, grid_path
    tried = [(str(tagged_path("panel_treatment", ".parquet", tag)), str(tagged_path("grid_geometry", ".geojson", tag))) for tag in candidates]
    raise FileNotFoundError(f"No matching treatment/grid artifacts found. Tried: {tried}")

GRID_TAG, PANEL_TREATMENT_PATH, GRID_GEOMETRY_PATH = resolve_grid_artifacts()
USING_INTENDED_GRID = GRID_TAG == INTENDED_GRID_TAG

# --- Pre-treatment freezing rules ---
FREEZE_END_YEAR_NEVER_TREATED = 2013
MIN_PRE_YEARS_FOR_TRENDS = 3

# --- Coca cultivation source (UNODC/SIMCI Grillas 1km grid) ---
# This grid only covers cells where coca has plausibly been present; it is not national.
# Cells outside its extent are left missing (NaN), not assumed to be zero coca.
GRILLAS_ZIP_PATH = PROJECT_ROOT / "data" / "Grillas_1k_2001_2023_.zip"
COCA_PANEL_PATH = INTERMEDIATE_DIR / f"panel_coca_{GRID_TAG}.parquet"

# --- Earth Engine export controls ---
GEE_PROJECT = PROJECT_CONFIG.get("gee_project", "ee-cpedrazaj97")
RUN_GEE_EXPORTS = False
AUTO_START_EXPORT_TASKS = True
GEE_EXPORT_FOLDER = f"gee_covariates_core_{GRID_TAG}"
GEE_EXPORT_PREFIX = f"core_covariates_{GRID_TAG}"
GEE_SCALE_NTL = 1000
GEE_SCALE_TERRAIN = 90
GEE_SCALE_POPULATION = 100
GEE_TILE_SCALE = 16
N_GRID_CHUNKS = 64 if GRID_TAG == "1km" else 8
GRID_CHUNK_SEED = 42

# After Drive download, put the CSVs in this local directory. In practice, the downloaded
# export files can land in a Drive-synced folder or a task folder with a chunk retry file that
# replaces the failed original chunk (e.g. *_chunk58_retry.csv).
LOCAL_GEE_COVARIATE_DIR = RAW_DIR / GEE_EXPORT_FOLDER
GEE_EXPORT_DIR_CANDIDATES = [
    LOCAL_GEE_COVARIATE_DIR,
    RAW_DIR / "gee_exports_20260513_133313",
    RAW_DIR / "gee_exports_20260404_111846",
    Path.home() / "Google Drive" / "My Drive" / GEE_EXPORT_FOLDER,
    Path.home() / "Google Drive" / "My Drive" / "gee_exports_20260513_133313",
    Path.home() / "Google Drive" / "My Drive" / "gee_exports_20260404_111846",
    Path.home() / "Google Drive" / "My Drive" / "Colombia covariates",
    Path.home() / "Google Drive" / "My Drive" / "gee_covariates_core_1km",
]
GEE_EXPORT_DIR_CANDIDATES = [p for p in dict.fromkeys(GEE_EXPORT_DIR_CANDIDATES)]
# Terrain (SRTM) and nightlights (DMSP/VIIRS) are exported separately because they need very
# different reduceRegions scales -- see the export cell below for why.
GEE_TERRAIN_GLOB = f"{GEE_EXPORT_PREFIX}_terrain*.csv"
GEE_NTL_GLOB = f"{GEE_EXPORT_PREFIX}_ntl*.csv"
GEE_POPULATION_GLOB = f"{GEE_EXPORT_PREFIX}_population*.csv"
# Backward-compatible single-file names, useful for small dev grids.
GEE_TERRAIN_CSV = LOCAL_GEE_COVARIATE_DIR / f"{GEE_EXPORT_PREFIX}_terrain.csv"
GEE_NTL_CSV = LOCAL_GEE_COVARIATE_DIR / f"{GEE_EXPORT_PREFIX}_ntl.csv"
GEE_POPULATION_CSV = LOCAL_GEE_COVARIATE_DIR / f"{GEE_EXPORT_PREFIX}_population.csv"

# --- Outputs ---
# Tagged with GRID_TAG to match the convention notebooks 07/08 use (append_tag_to_filename)
# when they look for this file -- an untagged name here would make USE_CORE_COVARIATES
# silently find nothing.
CORE_COVARIATE_PATH = INTERMEDIATE_DIR / f"panel_core_covariates_{GRID_TAG}.parquet"
BALANCE_SUMMARY_PATH = TABLE_DIR / "04_covariate_balance_summary.csv"
SOURCE_CATALOG_PATH = TABLE_DIR / "04_covariate_source_catalog.csv"

print("Intended grid tag:", INTENDED_GRID_TAG)
print("Active grid tag:", GRID_TAG)
print("Using intended production grid:", USING_INTENDED_GRID)
if not USING_INTENDED_GRID:
    print("WARNING: running with legacy/development grid artifacts. Re-run after Notebook 01/02 produce 1km artifacts.")
print("Treatment panel:", PANEL_TREATMENT_PATH)
print("Grid geometry:", GRID_GEOMETRY_PATH)
print("Common never-treated baseline ends in:", FREEZE_END_YEAR_NEVER_TREATED)
print("Run GEE exports:", RUN_GEE_EXPORTS)
print("GEE export chunks:", N_GRID_CHUNKS)

Intended grid tag: 1km
Active grid tag: 1km
Using intended production grid: True
Treatment panel: C:\Users\cpedr\OneDrive - Hertie School\PhD\Paper 2\paper2\data\intermediate\panel_treatment_1km.parquet
Grid geometry: C:\Users\cpedr\OneDrive - Hertie School\PhD\Paper 2\paper2\data\intermediate\grid_geometry_1km.geojson
Common never-treated baseline ends in: 2013
Run GEE exports: False
GEE export chunks: 64

## Verify active grid support

The row unit must be the Notebook 01 grid cell. Earth Engine source pixels are reduced inside these grid polygons; they do not define the panel unit.

In [3]:
grid_check_gdf = gpd.read_file(GRID_GEOMETRY_PATH)
if "cell_id" not in grid_check_gdf.columns:
    raise ValueError("Grid geometry is missing cell_id.")

area_km2 = grid_check_gdf.to_crs("EPSG:3857").geometry.area / 1e6
print("Grid cells:", f"{len(grid_check_gdf):,}")
print("Median cell area km2:", round(float(area_km2.median()), 3))
print("Cell area p05/p95 km2:", round(float(area_km2.quantile(0.05)), 3), round(float(area_km2.quantile(0.95)), 3))

if USING_INTENDED_GRID and not (0.5 <= area_km2.median() <= 1.5):
    raise ValueError("Active grid tag is 1km, but median cell area is not close to 1 km2.")
if not USING_INTENDED_GRID:
    print("Development note: this is not the intended 1km production grid.")

Grid cells: 1,160,018
Median cell area km2: 1.0
Cell area p05/p95 km2: 1.0 1.0

## Covariate source catalog

This table is deliberately explicit. It records the source, unit, timing rule, and frozen output name before any data are merged.

In [4]:
covariate_catalog = pd.DataFrame([
    {
        "covariate": "forest_loss_pre_mean_m2",
        "source": "Notebook 01 Hansen Global Forest Change panel, UMD/hansen/global_forest_change_2025_v1_13",
        "unit": "m2 forest loss per cell-year",
        "timing_rule": "Mean over years < first_treat_year for treated cells; mean over years <= FREEZE_END_YEAR_NEVER_TREATED for never-treated cells.",
        "status": "implemented_from_upstream_panel",
    },
    {
        "covariate": "forest_loss_pre_trend_m2_per_year",
        "source": "Notebook 01 Hansen Global Forest Change panel, UMD/hansen/global_forest_change_2025_v1_13",
        "unit": "m2 forest loss per year",
        "timing_rule": "OLS slope from pre-treatment forest-loss series; requires MIN_PRE_YEARS_FOR_TRENDS valid pre-treatment years.",
        "status": "implemented_from_upstream_panel",
    },
    {
        "covariate": "forest_loss_pre_sd_m2",
        "source": "Notebook 01 Hansen Global Forest Change panel, UMD/hansen/global_forest_change_2025_v1_13",
        "unit": "standard deviation of m2 forest loss per cell-year",
        "timing_rule": "Standard deviation over the same pre-treatment forest-loss window.",
        "status": "implemented_from_upstream_panel",
    },
    {
        "covariate": "coca_pre_mean_ha",
        "source": "UNODC/SIMCI Grillas 1km coca cultivation grid, data/Grillas_1k_2001_2023_.zip, spatially joined onto the project grid by centroid-in-polygon",
        "unit": "hectares of coca per cell-year, cell mean",
        "timing_rule": "Mean over years < first_treat_year for treated cells; mean over years <= FREEZE_END_YEAR_NEVER_TREATED for never-treated cells. Cells outside the Grillas grid's ~137k-cell extent are missing (not monitored), not zero.",
        "status": "implemented_from_local_shapefile",
    },
    {
        "covariate": "dmsp_stable_lights_pre_mean",
        "source": "NOAA/DMSP-OLS/NIGHTTIME_LIGHTS, stable_lights band",
        "unit": "digital number, 0-63, cell mean",
        "timing_rule": "Mean over available annual DMSP years before treatment; never-treated cells use years <= FREEZE_END_YEAR_NEVER_TREATED.",
        "status": "gee_export_then_freeze",
    },
    {
        "covariate": "viirs_avg_rad_pre_mean",
        "source": "NOAA/VIIRS/DNB/MONTHLY_V1/VCMCFG, avg_rad band",
        "unit": "nanoWatts/cm2/sr, annualized cell mean",
        "timing_rule": "Mean over available annual VIIRS years before treatment; cells treated before VIIRS begins remain missing.",
        "status": "gee_export_then_freeze",
    },
    {
        "covariate": "elevation_m_mean",
        "source": "USGS/SRTMGL1_003",
        "unit": "meters above sea level, cell mean",
        "timing_rule": "Static topography from SRTM; treated as pre-treatment geography.",
        "status": "gee_export_static",
    },
    {
        "covariate": "slope_deg_mean",
        "source": "USGS/SRTMGL1_003 transformed with ee.Terrain.slope",
        "unit": "degrees, cell mean",
        "timing_rule": "Static topography from SRTM; treated as pre-treatment geography.",
        "status": "gee_export_static",
    },
    {
        "covariate": "ruggedness_m_mean",
        "source": "USGS/SRTMGL1_003 local elevation standard deviation",
        "unit": "meters, cell mean",
        "timing_rule": "Static topography from SRTM; treated as pre-treatment geography.",
        "status": "gee_export_static",
    },
    {
        "covariate": "population_2000_sum",
        "source": "WorldPop/GP/100m/pop, Colombia image for year 2000",
        "unit": "estimated residents per grid cell",
        "timing_rule": "Baseline year 2000, before the forest-loss panel starts.",
        "status": "gee_export_baseline",
    },
    {
        "covariate": "friction_2019_mean",
        "source": "Oxford/MAP/friction_surface_2019",
        "unit": "travel impedance; higher values imply slower travel",
        "timing_rule": "Not pre-treatment for all designs. Use only as a geographic accessibility proxy or sensitivity check.",
        "status": "candidate_not_exported_by_default",
    },
    {
        "covariate": "distance_to_roads_km",
        "source": "External road vector source, preferably OpenStreetMap/official national road network, uploaded or processed outside GEE",
        "unit": "km from grid-cell centroid or cell polygon to nearest road",
        "timing_rule": "Use a baseline road vintage if available; otherwise label as time-invariant infrastructure proxy and test sensitivity.",
        "status": "external_needed",
    },
])

covariate_catalog.to_csv(SOURCE_CATALOG_PATH, index=False)
display(covariate_catalog)
print("Saved catalog:", SOURCE_CATALOG_PATH)

,covariate,source,unit,timing_rule,status
0,forest_loss_pre_mean_m2,"Notebook 01 Hansen Global Forest Change panel,...",m2 forest loss per cell-year,Mean over years < first_treat_year for treated...,implemented_from_upstream_panel
1,forest_loss_pre_trend_m2_per_year,"Notebook 01 Hansen Global Forest Change panel,...",m2 forest loss per year,OLS slope from pre-treatment forest-loss serie...,implemented_from_upstream_panel
2,forest_loss_pre_sd_m2,"Notebook 01 Hansen Global Forest Change panel,...",standard deviation of m2 forest loss per cell-...,Standard deviation over the same pre-treatment...,implemented_from_upstream_panel
3,coca_pre_mean_ha,"UNODC/SIMCI Grillas 1km coca cultivation grid,...","hectares of coca per cell-year, cell mean",Mean over years < first_treat_year for treated...,implemented_from_local_shapefile
4,dmsp_stable_lights_pre_mean,"NOAA/DMSP-OLS/NIGHTTIME_LIGHTS, stable_lights ...","digital number, 0-63, cell mean",Mean over available annual DMSP years before t...,gee_export_then_freeze
5,viirs_avg_rad_pre_mean,"NOAA/VIIRS/DNB/MONTHLY_V1/VCMCFG, avg_rad band","nanoWatts/cm2/sr, annualized cell mean",Mean over available annual VIIRS years before ...,gee_export_then_freeze
6,elevation_m_mean,USGS/SRTMGL1_003,"meters above sea level, cell mean",Static topography from SRTM; treated as pre-tr...,gee_export_static
7,slope_deg_mean,USGS/SRTMGL1_003 transformed with ee.Terrain.s...,"degrees, cell mean",Static topography from SRTM; treated as pre-tr...,gee_export_static
8,ruggedness_m_mean,USGS/SRTMGL1_003 local elevation standard devi...,"meters, cell mean",Static topography from SRTM; treated as pre-tr...,gee_export_static
9,population_2000_sum,"WorldPop/GP/100m/pop, Colombia image for year ...",estimated residents per grid cell,"Baseline year 2000, before the forest-loss pan...",gee_export_baseline
10,friction_2019_mean,Oxford/MAP/friction_surface_2019,travel impedance; higher values imply slower t...,Not pre-treatment for all designs. Use only as...,candidate_not_exported_by_default
11,distance_to_roads_km,"External road vector source, preferably OpenSt...",km from grid-cell centroid or cell polygon to ...,Use a baseline road vintage if available; othe...,external_needed

Saved catalog: C:\Users\cpedr\OneDrive - Hertie School\PhD\Paper 2\paper2\outputs\tables\04_covariate_source_catalog.csv

## Load treatment panel and freeze forest-loss history

Forest-loss covariates come from Notebook 01 / Notebook 02 outputs. They are cell-level summaries and are not allowed to use treated or post-treatment years.

In [5]:
if not PANEL_TREATMENT_PATH.exists():
    raise FileNotFoundError(PANEL_TREATMENT_PATH)

panel = pd.read_parquet(PANEL_TREATMENT_PATH)
required_cols = {"cell_id", "year", "loss_m2", "first_treat_year", "ever_treated", "never_treated"}
missing = required_cols.difference(panel.columns)
if missing:
    raise ValueError(f"Treatment panel is missing required columns: {sorted(missing)}")

cell_timing = (
    panel[["cell_id", "first_treat_year", "ever_treated", "never_treated", "cell_lon", "cell_lat", "base_m2"]]
    .drop_duplicates("cell_id")
    .copy()
)

panel_for_freeze = panel[["cell_id", "year", "loss_m2", "first_treat_year", "ever_treated", "never_treated"]].copy()
panel_for_freeze["freeze_cutoff_year"] = np.where(
    panel_for_freeze["ever_treated"].eq(1),
    panel_for_freeze["first_treat_year"].astype("float") - 1,
    FREEZE_END_YEAR_NEVER_TREATED,
)
panel_pre = panel_for_freeze[panel_for_freeze["year"] <= panel_for_freeze["freeze_cutoff_year"]].copy()

print("Cells:", cell_timing["cell_id"].nunique())
print("Panel years:", int(panel["year"].min()), "to", int(panel["year"].max()))
print("Pre-treatment forest rows retained:", f"{len(panel_pre):,}")

Cells: 1160018
Panel years: 2001 to 2025
Pre-treatment forest rows retained: 13,519,778

In [6]:
def slope_or_nan(years, values, min_obs=3):
    mask = np.isfinite(years) & np.isfinite(values)
    years = np.asarray(years)[mask]
    values = np.asarray(values)[mask]
    if len(years) < min_obs or np.nanstd(years) == 0:
        return np.nan
    x = years - years.mean()
    return float(np.sum(x * (values - values.mean())) / np.sum(x * x))

forest_covariates = (
    panel_pre.groupby("cell_id", as_index=False)
    .agg(
        forest_loss_pre_years=("year", "nunique"),
        forest_loss_pre_mean_m2=("loss_m2", "mean"),
        forest_loss_pre_sd_m2=("loss_m2", "std"),
        forest_loss_pre_total_m2=("loss_m2", "sum"),
    )
)

forest_trends = (
    panel_pre.groupby("cell_id")
    .apply(lambda x: slope_or_nan(x["year"].to_numpy(dtype=float), x["loss_m2"].to_numpy(dtype=float), MIN_PRE_YEARS_FOR_TRENDS), include_groups=False)
    .rename("forest_loss_pre_trend_m2_per_year")
    .reset_index()
)

forest_covariates = forest_covariates.merge(forest_trends, on="cell_id", how="left")
forest_covariates["forest_loss_pre_sd_m2"] = forest_covariates["forest_loss_pre_sd_m2"].fillna(0)

print(forest_covariates.shape)
display(forest_covariates.head())

(1037163, 6)

,cell_id,forest_loss_pre_years,forest_loss_pre_mean_m2,forest_loss_pre_sd_m2,forest_loss_pre_total_m2,forest_loss_pre_trend_m2_per_year
0,lon_-66.875081_lat_1.226107,13,0.000000,0.000000,0.000000,0.000000
1,lon_-66.875081_lat_1.235088,13,0.000000,0.000000,0.000000,0.000000
2,lon_-66.875081_lat_1.244069,13,0.000000,0.000000,0.000000,0.000000
3,lon_-66.884064_lat_1.226107,13,0.000000,0.000000,0.000000,0.000000
4,lon_-66.884064_lat_1.235088,13,68.751751,247.887964,893.772766,24.554197

## Coca cultivation panel (UNODC/SIMCI Grillas 1km grid)

Source: `Grillas_1k_2001_2023_.zip`, a 1km grid with annual coca-hectare columns (`COCA_2001`...`COCA_2023`) on its own grid (`GRI_1K_F`), not the project's `cell_id`. It only covers cells where coca has plausibly been present (~137k cells), not the full national grid, so it is spatially joined onto the project grid by centroid-in-polygon. Cells outside the Grillas extent are left missing (NaN), not assumed to be zero coca -- "not monitored" and "monitored, zero hectares" are not the same claim.

This produces two things: a full annual panel (`panel_coca_{GRID_TAG}.parquet`, all years, for descriptive/time-series use) and a frozen pre-treatment covariate (`coca_pre_mean_ha`, same freezing rule as forest loss and nightlights, for the causal covariate table).

In [7]:
if not GRILLAS_ZIP_PATH.exists():
    raise FileNotFoundError(GRILLAS_ZIP_PATH)

coca_raw = gpd.read_file(f"zip://{GRILLAS_ZIP_PATH}")
coca_year_cols = [c for c in coca_raw.columns if c.startswith("COCA_")]
print("Coca source cells:", f"{len(coca_raw):,}")
print("Coca years:", coca_year_cols[0], "to", coca_year_cols[-1])

coca_points = coca_raw[["GRI_1K_F"] + coca_year_cols].copy()
coca_points["geometry"] = coca_raw.geometry.centroid
coca_points = gpd.GeoDataFrame(coca_points, geometry="geometry", crs=coca_raw.crs).to_crs(grid_check_gdf.crs)

minx, miny, maxx, maxy = coca_points.total_bounds
grid_candidates = grid_check_gdf.cx[minx:maxx, miny:maxy][["cell_id", "geometry"]]
print("Project grid cells in coca bounding box:", f"{len(grid_candidates):,}")

coca_joined = gpd.sjoin(coca_points, grid_candidates, predicate="within", how="inner")
# Guard against a centroid landing exactly on a shared grid edge and matching more than one
# project cell; keep the first match per source cell rather than double-counting hectares.
coca_joined = coca_joined.drop_duplicates("GRI_1K_F", keep="first")
print(
    "Coca source cells matched to a project grid cell:",
    f"{len(coca_joined):,}", "of", f"{len(coca_points):,}",
)

coca_wide = coca_joined.groupby("cell_id", as_index=False)[coca_year_cols].sum()

coca_long = coca_wide.melt(id_vars="cell_id", value_vars=coca_year_cols, var_name="coca_year_col", value_name="coca_ha")
coca_long["year"] = coca_long["coca_year_col"].str.replace("COCA_", "", regex=False).astype(int)
coca_long = coca_long.drop(columns="coca_year_col").sort_values(["cell_id", "year"]).reset_index(drop=True)

coca_long.to_parquet(COCA_PANEL_PATH, index=False)
print("Saved coca panel:", COCA_PANEL_PATH)
print("Project cells with any coca coverage:", f"{coca_long['cell_id'].nunique():,}", "of", f"{cell_timing['cell_id'].nunique():,}")
print(coca_long.shape)
display(coca_long.head())

Coca source cells: 137,032
Coca years: COCA_2001 to COCA_2023
Project grid cells in coca bounding box: 1,128,575
Coca source cells matched to a project grid cell: 136,719 of 137,032
Saved coca panel: C:\Users\cpedr\OneDrive - Hertie School\PhD\Paper 2\paper2\data\intermediate\panel_coca_1km.parquet
Project cells with any coca coverage: 136,704 of 1,160,018
(3144192, 3)

                       cell_id  coca_ha  year
0  lon_-67.620683_lat_3.711934      0.0  2001
1  lon_-67.620683_lat_3.711934      0.0  2002
2  lon_-67.620683_lat_3.711934      0.0  2003
3  lon_-67.620683_lat_3.711934      0.0  2004
4  lon_-67.620683_lat_3.711934      0.0  2005

In [8]:
coca_panel_for_freeze = coca_long.merge(
    cell_timing[["cell_id", "first_treat_year", "ever_treated", "never_treated"]],
    on="cell_id",
    how="inner",
)
coca_panel_for_freeze["freeze_cutoff_year"] = np.where(
    coca_panel_for_freeze["ever_treated"].eq(1),
    coca_panel_for_freeze["first_treat_year"].astype("float") - 1,
    FREEZE_END_YEAR_NEVER_TREATED,
)
coca_pre = coca_panel_for_freeze[coca_panel_for_freeze["year"] <= coca_panel_for_freeze["freeze_cutoff_year"]].copy()

coca_covariates = (
    coca_pre.groupby("cell_id", as_index=False)
    .agg(
        coca_pre_years=("year", "nunique"),
        coca_pre_mean_ha=("coca_ha", "mean"),
    )
)

print(coca_covariates.shape)
display(coca_covariates.head())

(128315, 3)

                       cell_id  coca_pre_years  coca_pre_mean_ha
0  lon_-67.620683_lat_3.711934              13          0.117692
1  lon_-67.620683_lat_3.756755              13          0.083077
2  lon_-67.647632_lat_3.810536              13          0.055385
3  lon_-67.656616_lat_3.819499              13          0.221538
4  lon_-67.665599_lat_3.810536              13          0.173077

## Optional Earth Engine export: night lights, terrain, and population

Run this section only when you want to create or refresh the GEE-derived covariate CSVs. It uses the exact grid geometry from Notebook 01, converts it to an Earth Engine feature collection, and exports one row per grid cell. For the 1km grid, exports are chunked so Earth Engine does not need to write the whole national table in one task.

Sources checked against the Earth Engine catalog:

- DMSP yearly nighttime lights: `NOAA/DMSP-OLS/NIGHTTIME_LIGHTS`
- VIIRS monthly nighttime lights: `NOAA/VIIRS/DNB/MONTHLY_V1/VCMCFG`
- SRTM elevation: `USGS/SRTMGL1_003`
- WorldPop population: `WorldPop/GP/100m/pop`

In [9]:
if RUN_GEE_EXPORTS:
    import ee
    import geemap

    try:
        ee.Initialize(project=GEE_PROJECT)
        print("Earth Engine initialized successfully.")
    except Exception:
        ee.Authenticate()
        ee.Initialize(project=GEE_PROJECT)
        print("Earth Engine initialized successfully after authentication.")

    # The national grid has ~1.1M cells for the 1km production grid. Converting that many
    # features with geemap.gdf_to_ee builds one giant client-side FeatureCollection literal,
    # and every downstream .start()/.getInfo() call has to re-serialize and upload the whole
    # thing, not just the filtered chunk. That made every export task submission hang for
    # many minutes. Fix: upload the grid ONCE as an EE table asset, then have every export
    # reference it by asset ID so nothing re-embeds the full geometry per call.
    GEE_GRID_ASSET_ID = f"projects/{GEE_PROJECT}/assets/grid_geometry_{GRID_TAG}_shp"

    def _grid_asset_exists(asset_id):
        try:
            ee.data.getAsset(asset_id)
            return True
        except ee.EEException:
            return False

    if not _grid_asset_exists(GEE_GRID_ASSET_ID):
        raise RuntimeError(
            "Grid table asset not found: "
            f"{GEE_GRID_ASSET_ID}\n\n"
            "For a grid this large (~1.1M features), upload it once as an EE table asset "
            "before running exports, using either:\n"
            "  1) the Assets tab at https://code.earthengine.google.com/ (drag-and-drop the "
            f"file at {GRID_GEOMETRY_PATH}), or\n"
            "  2) the CLI: earthengine upload table "
            f"--asset_id={GEE_GRID_ASSET_ID} <path to grid geometry, staged in GCS if required>\n\n"
            "Wait for ingestion to finish (check the Tasks tab), then re-run this cell."
        )

    grid_ee = ee.FeatureCollection(GEE_GRID_ASSET_ID)

    def add_grid_chunk(f):
        chunk = ee.Number(f.get("grid_random")).multiply(N_GRID_CHUNKS).floor().int()
        return f.set("grid_chunk", chunk)

    grid_ee = grid_ee.randomColumn("grid_random", seed=GRID_CHUNK_SEED).map(add_grid_chunk)
    print("Grid asset:", GEE_GRID_ASSET_ID)
    print("Grid cells loaded from asset:", grid_ee.size().getInfo())
    print("Chunk count:", N_GRID_CHUNKS)

In [10]:
if RUN_GEE_EXPORTS:
    def dmsp_annual_band(year):
        img = (
            ee.ImageCollection("NOAA/DMSP-OLS/NIGHTTIME_LIGHTS")
            .filter(ee.Filter.calendarRange(year, year, "year"))
            .select("stable_lights")
            .mean()
            .rename(f"dmsp_stable_lights_{year}")
        )
        return img

    def viirs_annual_band(year):
        img = (
            ee.ImageCollection("NOAA/VIIRS/DNB/MONTHLY_V1/VCMCFG")
            .filterDate(f"{year}-01-01", f"{year + 1}-01-01")
            .select("avg_rad")
            .mean()
            .rename(f"viirs_avg_rad_{year}")
        )
        return img

    srtm = ee.Image("USGS/SRTMGL1_003").select("elevation")
    elevation = srtm.rename("elevation_m")
    slope = ee.Terrain.slope(srtm).rename("slope_deg")
    ruggedness = srtm.reduceNeighborhood(
        reducer=ee.Reducer.stdDev(),
        kernel=ee.Kernel.square(radius=1, units="pixels"),
    ).rename("ruggedness_m")
    terrain_img = ee.Image.cat([elevation, slope, ruggedness])

    dmsp_bands = [dmsp_annual_band(y) for y in range(2001, 2014)]
    viirs_bands = [viirs_annual_band(y) for y in range(2012, 2026)]
    ntl_img = ee.Image.cat(dmsp_bands + viirs_bands)

    # SRTM terrain (~30m native) and DMSP/VIIRS nightlights (~1km / ~500m native) need very
    # different reduceRegions scales. Reducing both together at the fine terrain scale forced
    # the coarse nightlight bands to be resampled far past their native resolution, which is
    # what pushed several chunks past Earth Engine's per-task compute-time budget ("Computation
    # timed out"). Exporting them as two images at their own GEE_SCALE_* values keeps each
    # task's workload proportional to the actual information being reduced.
    def export_image_by_chunk(image, scale, name_tag):
        tasks = {}
        for chunk in range(N_GRID_CHUNKS):
            chunk_fc = grid_ee.filter(ee.Filter.eq("grid_chunk", chunk))
            reduced = image.reduceRegions(
                collection=chunk_fc,
                reducer=ee.Reducer.mean(),
                scale=scale,
                tileScale=GEE_TILE_SCALE,
            )
            description = f"{GEE_EXPORT_PREFIX}_{name_tag}_chunk{chunk:02d}"
            task = ee.batch.Export.table.toDrive(
                collection=reduced,
                description=description,
                folder=GEE_EXPORT_FOLDER,
                fileNamePrefix=description,
                fileFormat="CSV",
            )
            tasks[description] = task
            if AUTO_START_EXPORT_TASKS:
                task.start()
        return tasks

    terrain_tasks = export_image_by_chunk(terrain_img, GEE_SCALE_TERRAIN, "terrain")
    ntl_tasks = export_image_by_chunk(ntl_img, GEE_SCALE_NTL, "ntl")
    print(("Started" if AUTO_START_EXPORT_TASKS else "Prepared"), len(terrain_tasks), "terrain covariate export task(s).")
    print(("Started" if AUTO_START_EXPORT_TASKS else "Prepared"), len(ntl_tasks), "night-lights covariate export task(s).")

In [11]:
if RUN_GEE_EXPORTS:
    pop2000 = (
        ee.ImageCollection("WorldPop/GP/100m/pop")
        .filter(ee.Filter.eq("country", "COL"))
        .filter(ee.Filter.eq("year", 2000))
        .first()
        .select("population")
        .rename("population_2000")
    )

    population_tasks = {}
    for chunk in range(N_GRID_CHUNKS):
        chunk_fc = grid_ee.filter(ee.Filter.eq("grid_chunk", chunk))
        reduced = pop2000.reduceRegions(
            collection=chunk_fc,
            reducer=ee.Reducer.sum(),
            scale=GEE_SCALE_POPULATION,
            tileScale=GEE_TILE_SCALE,
        )
        description = f"{GEE_EXPORT_PREFIX}_population_chunk{chunk:02d}"
        task = ee.batch.Export.table.toDrive(
            collection=reduced,
            description=description,
            folder=GEE_EXPORT_FOLDER,
            fileNamePrefix=description,
            fileFormat="CSV",
        )
        population_tasks[description] = task
        if AUTO_START_EXPORT_TASKS:
            task.start()
    print(("Started" if AUTO_START_EXPORT_TASKS else "Prepared"), len(population_tasks), "population covariate export task(s).")

## Download Earth Engine exports from Google Drive

Same logic as Notebook 01's Drive download step: reuse the cached OAuth token at `configs/google_drive_token.json` (no new authorization needed if Notebook 01 already ran), find the `GEE_EXPORT_FOLDER` folder by name, and download each expected chunk CSV by exact filename, skipping anything already present locally.

The retried chunk (`ntl_chunk58`, after its `Computation timed out` failure) was re-submitted with the same `fileNamePrefix`, so it is expected under the same filename as every other chunk -- no special-cased filename is needed. `find_drive_file` is still written to tolerate two files sharing a name (picking the most recently modified) in case Drive ever ends up with a leftover from the failed attempt alongside the retry's output.

In [12]:
import io
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload

DRIVE_SCOPES = ["https://www.googleapis.com/auth/drive.readonly"]
DRIVE_CLIENT_SECRET_FILE = PROJECT_ROOT / "configs" / "google_drive_client_secret.json"
DRIVE_TOKEN_FILE = PROJECT_ROOT / "configs" / "google_drive_token.json"


def get_drive_service(client_secret_file=DRIVE_CLIENT_SECRET_FILE, token_file=DRIVE_TOKEN_FILE, scopes=DRIVE_SCOPES):
    creds = None
    if Path(token_file).exists():
        creds = Credentials.from_authorized_user_file(str(token_file), scopes)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(str(client_secret_file), scopes)
            creds = flow.run_local_server(port=0)
        Path(token_file).parent.mkdir(parents=True, exist_ok=True)
        with open(token_file, "w") as f:
            f.write(creds.to_json())

    return build("drive", "v3", credentials=creds)


def find_drive_folder_id(service, folder_name):
    q = f"name = '{folder_name}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false"
    results = service.files().list(q=q, spaces="drive", fields="files(id, name, modifiedTime)", orderBy="modifiedTime desc").execute()
    files = results.get("files", [])
    if not files:
        raise FileNotFoundError(f"Drive folder '{folder_name}' not found.")
    if len(files) != 1:
        print(f"Found {len(files)} folders named '{folder_name}':")
        for f in files[:20]:
            print(" -", f["id"], f["name"], f.get("modifiedTime"))
        raise RuntimeError(f"Ambiguous Drive folder name '{folder_name}'. Use a unique folder name per run and delete duplicates.")
    return files[0]["id"]


def find_drive_file(service, folder_id, filename):
    q = f"name = '{filename}' and '{folder_id}' in parents and trashed = false"
    results = service.files().list(q=q, spaces="drive", fields="files(id, name, mimeType, modifiedTime, size)", orderBy="modifiedTime desc").execute()
    files = results.get("files", [])
    if not files:
        raise FileNotFoundError(f"Drive file '{filename}' not found in folder ID {folder_id}.")
    if len(files) > 1:
        # A retried chunk (e.g. the ntl chunk58 timeout) can in principle leave more than one
        # file with the same exported name. Take the most recently modified one -- orderBy
        # already puts it first -- instead of raising, since this is an expected situation here.
        print(f"Found {len(files)} files named '{filename}'; using the most recently modified one.")
        for f in files[:5]:
            print(" -", f["id"], f["name"], f.get("modifiedTime"), f.get("size"))
    return files[0]


def download_drive_file(service, file_id, destination_path):
    destination_path = Path(destination_path)
    destination_path.parent.mkdir(parents=True, exist_ok=True)
    request = service.files().get_media(fileId=file_id)
    fh = io.BytesIO()
    downloader = MediaIoBaseDownload(fh, request)
    done = False
    while not done:
        status, done = downloader.next_chunk()
    with open(destination_path, "wb") as f:
        f.write(fh.getvalue())
    print("Saved to:", destination_path)

In [13]:
AUTO_DOWNLOAD_GEE_FROM_DRIVE = True


def expected_gee_chunk_filenames(prefix, name_tag, n_chunks):
    return [f"{prefix}_{name_tag}_chunk{chunk:02d}.csv" for chunk in range(n_chunks)]


expected_gee_filenames = (
    expected_gee_chunk_filenames(GEE_EXPORT_PREFIX, "terrain", N_GRID_CHUNKS)
    + expected_gee_chunk_filenames(GEE_EXPORT_PREFIX, "ntl", N_GRID_CHUNKS)
    + expected_gee_chunk_filenames(GEE_EXPORT_PREFIX, "population", N_GRID_CHUNKS)
)

LOCAL_GEE_COVARIATE_DIR.mkdir(parents=True, exist_ok=True)

if AUTO_DOWNLOAD_GEE_FROM_DRIVE:
    drive_service = get_drive_service()
    gee_folder_id = find_drive_folder_id(drive_service, GEE_EXPORT_FOLDER)

    downloaded, already_local = 0, 0
    for filename in expected_gee_filenames:
        local_path = LOCAL_GEE_COVARIATE_DIR / filename
        if local_path.exists() and local_path.stat().st_size > 0:
            already_local += 1
            continue
        drive_file = find_drive_file(drive_service, gee_folder_id, filename)
        download_drive_file(drive_service, drive_file["id"], local_path)
        downloaded += 1

    print(f"Downloaded {downloaded} file(s); {already_local} were already local.")
else:
    print("AUTO_DOWNLOAD_GEE_FROM_DRIVE = False. Expecting GEE export CSVs to already be present locally.")

missing = [f for f in expected_gee_filenames if not (LOCAL_GEE_COVARIATE_DIR / f).exists()]
if missing:
    print(f"WARNING: {len(missing)} of {len(expected_gee_filenames)} expected export file(s) are still missing locally (likely still running or failed on Earth Engine's side):")
    for f in missing[:20]:
        print(" -", f)
    if len(missing) > 20:
        print(" ...")
else:
    print("All", len(expected_gee_filenames), "expected GEE export files are present locally.")

Downloaded 0 file(s); 192 were already local.
All 192 expected GEE export files are present locally.

## Load GEE covariate exports if available

This block is intentionally tolerant: notebook 04 can already build the forest-history covariates before the GEE CSVs are downloaded. Once the CSVs exist locally, rerun from here to merge and freeze them.

In [14]:
def _gee_chunk_sort_key(path):
    name = path.name
    match = re.search(r"chunk(\d+)", name)
    chunk_num = int(match.group(1)) if match else 10**9
    retry_penalty = 1 if "_retry" in name else 0
    return (chunk_num, retry_penalty, name)


def _gee_retry_preferred_key(path):
    name = path.name
    if name.endswith("_retry.csv"):
        return name.replace("_retry.csv", ".csv")
    return name


def read_gee_csvs_if_available(directory_candidates, glob_pattern, fallback_path=None):
    if isinstance(directory_candidates, (str, Path)):
        directory_candidates = [Path(directory_candidates)]
    else:
        directory_candidates = [Path(d) for d in directory_candidates]

    files = []
    for directory in directory_candidates:
        if directory.exists():
            files.extend(sorted(directory.glob(glob_pattern)))

    if not files and fallback_path is not None and Path(fallback_path).exists():
        files = [Path(fallback_path)]

    if not files:
        print("Missing optional GEE export(s):", glob_pattern)
        return None

    chosen = {}
    for path in files:
        key = _gee_retry_preferred_key(path)
        current = chosen.get(key)
        if current is None:
            chosen[key] = path
        elif "_retry" in path.name and "_retry" not in current.name:
            chosen[key] = path
        elif "_retry" in path.name and "_retry" in current.name:
            if _gee_chunk_sort_key(path) < _gee_chunk_sort_key(current):
                chosen[key] = path

    files = sorted(chosen.values(), key=_gee_chunk_sort_key)

    frames = []
    for path in files:
        df = pd.read_csv(path)
        if "cell_id" not in df.columns:
            raise ValueError(f"{path} does not contain cell_id")
        drop_cols = [c for c in ["system:index", ".geo", "id", "grid_random", "grid_chunk"] if c in df.columns]
        if drop_cols:
            df = df.drop(columns=drop_cols)
        frames.append(df)

    out = pd.concat(frames, ignore_index=True)
    out = out.drop_duplicates("cell_id", keep="last")
    print("Loaded", len(files), "file(s) with", f"{len(out):,}", "unique cells from", glob_pattern)
    return out

terrain_gee = read_gee_csvs_if_available(GEE_EXPORT_DIR_CANDIDATES, GEE_TERRAIN_GLOB, GEE_TERRAIN_CSV)
ntl_gee = read_gee_csvs_if_available(GEE_EXPORT_DIR_CANDIDATES, GEE_NTL_GLOB, GEE_NTL_CSV)
population_gee = read_gee_csvs_if_available(GEE_EXPORT_DIR_CANDIDATES, GEE_POPULATION_GLOB, GEE_POPULATION_CSV)

gee_covariates = cell_timing[["cell_id"]].copy()
for continuous_frame in [terrain_gee, ntl_gee]:
    if continuous_frame is not None:
        gee_covariates = gee_covariates.merge(continuous_frame, on="cell_id", how="left")
if population_gee is not None:
    pop_cols = ["cell_id"] + [c for c in population_gee.columns if c != "cell_id"]
    population_gee = population_gee[pop_cols].rename(columns={"population_2000": "population_2000_sum"})
    gee_covariates = gee_covariates.merge(population_gee, on="cell_id", how="left")

print(gee_covariates.shape)
display(gee_covariates.head())

Loaded 64 file(s) with 1,160,018 unique cells from core_covariates_1km_terrain*.csv
Loaded 64 file(s) with 1,160,018 unique cells from core_covariates_1km_ntl*.csv
Loaded 64 file(s) with 1,160,018 unique cells from core_covariates_1km_population*.csv
(1160018, 32)

,cell_id,elevation_m,ruggedness_m,slope_deg,dmsp_stable_lights_2001,dmsp_stable_lights_2002,dmsp_stable_lights_2003,dmsp_stable_lights_2004,dmsp_stable_lights_2005,dmsp_stable_lights_2006,dmsp_stable_lights_2007,dmsp_stable_lights_2008,dmsp_stable_lights_2009,dmsp_stable_lights_2010,dmsp_stable_lights_2011,dmsp_stable_lights_2012,dmsp_stable_lights_2013,viirs_avg_rad_2012,viirs_avg_rad_2013,viirs_avg_rad_2014,viirs_avg_rad_2015,viirs_avg_rad_2016,viirs_avg_rad_2017,viirs_avg_rad_2018,viirs_avg_rad_2019,viirs_avg_rad_2020,viirs_avg_rad_2021,viirs_avg_rad_2022,viirs_avg_rad_2023,viirs_avg_rad_2024,viirs_avg_rad_2025,sum
0,lon_-66.875081_lat_1.226107,103.159345,2.758786,2.421466,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.016272,0.051700,-0.003357,0.019555,0.015010,0.213900,0.144583,0.127708,0.167708,0.241667,0.211875,0.237083,0.310833,0.258958,0.264932
1,lon_-66.875081_lat_1.235088,101.573747,3.046243,2.662663,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.028045,0.046843,-0.007581,0.028978,-0.004850,0.188154,0.145833,0.151250,0.187708,0.243125,0.239583,0.254583,0.300000,0.252917,0.220351
2,lon_-66.875081_lat_1.244069,100.312506,3.114979,2.637995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.012060,0.029498,-0.032331,0.028009,-0.006872,0.208607,0.135417,0.142292,0.168958,0.210000,0.206250,0.233750,0.241875,0.248125,0.001014
3,lon_-66.884064_lat_1.226107,107.617527,2.093173,1.806414,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.012754,0.031168,-0.007921,0.044676,-0.018201,0.221400,0.178333,0.114375,0.183542,0.281042,0.218333,0.223958,0.306250,0.243125,0.387089
4,lon_-66.884064_lat_1.235088,102.933021,2.938862,2.617245,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.002054,0.028815,-0.012316,0.033166,0.019363,0.214511,0.151042,0.145417,0.171042,0.249167,0.226458,0.255000,0.284375,0.280000,0.464050

## Freeze time-varying GEE covariates

DMSP and VIIRS are annual series. This block converts annual columns into frozen pre-treatment summaries. Static terrain and baseline population are kept as cell-level values.

In [15]:
def find_year_columns(df, prefix):
    pattern = re.compile(rf"^{re.escape(prefix)}_(\d{{4}})$")
    pairs = []
    for col in df.columns:
        match = pattern.match(col)
        if match:
            pairs.append((int(match.group(1)), col))
    return sorted(pairs)

def frozen_row_mean(row, year_cols, first_treat_year, ever_treated, never_cutoff):
    values = []
    for year, col in year_cols:
        if ever_treated == 1:
            keep = pd.notna(first_treat_year) and year < int(first_treat_year)
        else:
            keep = year <= never_cutoff
        if keep:
            values.append(row.get(col, np.nan))
    values = pd.to_numeric(pd.Series(values), errors="coerce")
    return float(values.mean()) if values.notna().any() else np.nan

gee_frozen = gee_covariates.merge(
    cell_timing[["cell_id", "first_treat_year", "ever_treated"]],
    on="cell_id",
    how="left",
)

dmsp_cols = find_year_columns(gee_frozen, "dmsp_stable_lights")
viirs_cols = find_year_columns(gee_frozen, "viirs_avg_rad")

if dmsp_cols:
    gee_frozen["dmsp_stable_lights_pre_mean"] = gee_frozen.apply(
        lambda r: frozen_row_mean(r, dmsp_cols, r["first_treat_year"], r["ever_treated"], FREEZE_END_YEAR_NEVER_TREATED),
        axis=1,
    )
    gee_frozen["dmsp_stable_lights_pre_years"] = gee_frozen.apply(
        lambda r: sum((y < int(r["first_treat_year"]) if r["ever_treated"] == 1 and pd.notna(r["first_treat_year"]) else y <= FREEZE_END_YEAR_NEVER_TREATED) and pd.notna(r.get(c)) for y, c in dmsp_cols),
        axis=1,
    )

if viirs_cols:
    gee_frozen["viirs_avg_rad_pre_mean"] = gee_frozen.apply(
        lambda r: frozen_row_mean(r, viirs_cols, r["first_treat_year"], r["ever_treated"], FREEZE_END_YEAR_NEVER_TREATED),
        axis=1,
    )
    gee_frozen["viirs_avg_rad_pre_years"] = gee_frozen.apply(
        lambda r: sum((y < int(r["first_treat_year"]) if r["ever_treated"] == 1 and pd.notna(r["first_treat_year"]) else y <= FREEZE_END_YEAR_NEVER_TREATED) and pd.notna(r.get(c)) for y, c in viirs_cols),
        axis=1,
    )

static_cols = [c for c in ["elevation_m", "slope_deg", "ruggedness_m", "population_2000_sum"] if c in gee_frozen.columns]
rename_static = {
    "elevation_m": "elevation_m_mean",
    "slope_deg": "slope_deg_mean",
    "ruggedness_m": "ruggedness_m_mean",
}

keep_gee_cols = ["cell_id"] + static_cols + [
    c for c in [
        "dmsp_stable_lights_pre_mean",
        "dmsp_stable_lights_pre_years",
        "viirs_avg_rad_pre_mean",
        "viirs_avg_rad_pre_years",
    ] if c in gee_frozen.columns
]
gee_frozen = gee_frozen[keep_gee_cols].rename(columns=rename_static)

print(gee_frozen.shape)
display(gee_frozen.head())

(1160018, 8)

,cell_id,elevation_m_mean,slope_deg_mean,ruggedness_m_mean,dmsp_stable_lights_pre_mean,dmsp_stable_lights_pre_years,viirs_avg_rad_pre_mean,viirs_avg_rad_pre_years
0,lon_-66.875081_lat_1.226107,103.159345,2.421466,2.758786,0.0,13,0.017714,2
1,lon_-66.875081_lat_1.235088,101.573747,2.662663,3.046243,0.0,13,0.037444,2
2,lon_-66.875081_lat_1.244069,100.312506,2.637995,3.114979,0.0,13,0.008719,2
3,lon_-66.884064_lat_1.226107,107.617527,1.806414,2.093173,0.0,13,0.009207,2
4,lon_-66.884064_lat_1.235088,102.933021,2.617245,2.938862,0.0,13,0.013381,2

## Assemble core covariate table

The table is one row per grid cell. Estimation notebooks can merge it onto the panel by `cell_id`.

In [16]:
core_covariates = (
    cell_timing
    .merge(forest_covariates, on="cell_id", how="left")
    .merge(coca_covariates, on="cell_id", how="left")
    .merge(gee_frozen, on="cell_id", how="left")
)

# Drop duplicate columns if an optional export was not loaded cleanly.
core_covariates = core_covariates.loc[:, ~core_covariates.columns.duplicated()].copy()

ordered_front = [
    "cell_id", "cell_lon", "cell_lat", "base_m2",
    "first_treat_year", "ever_treated", "never_treated",
]
other_cols = [c for c in core_covariates.columns if c not in ordered_front]
core_covariates = core_covariates[ordered_front + other_cols]

core_covariates.to_parquet(CORE_COVARIATE_PATH, index=False)

print("Saved:", CORE_COVARIATE_PATH)
print(core_covariates.shape)
display(core_covariates.head())

Saved: C:\Users\cpedr\OneDrive - Hertie School\PhD\Paper 2\paper2\data\intermediate\panel_core_covariates_1km.parquet
(1160018, 21)

,cell_id,cell_lon,cell_lat,base_m2,first_treat_year,ever_treated,never_treated,forest_loss_pre_years,forest_loss_pre_mean_m2,forest_loss_pre_sd_m2,forest_loss_pre_total_m2,forest_loss_pre_trend_m2_per_year,coca_pre_years,coca_pre_mean_ha,elevation_m_mean,slope_deg_mean,ruggedness_m_mean,dmsp_stable_lights_pre_mean,dmsp_stable_lights_pre_years,viirs_avg_rad_pre_mean,viirs_avg_rad_pre_years
0,lon_-66.875081_lat_1.226107,-66.875081,1.226107,313112.147300,<NA>,0,1,13.0,0.000000,0.000000,0.000000,0.000000,NaN,NaN,103.159345,2.421466,2.758786,0.0,13,0.017714,2
1,lon_-66.875081_lat_1.235088,-66.875081,1.235088,546214.553899,<NA>,0,1,13.0,0.000000,0.000000,0.000000,0.000000,NaN,NaN,101.573747,2.662663,3.046243,0.0,13,0.037444,2
2,lon_-66.875081_lat_1.244069,-66.875081,1.244069,98707.347929,<NA>,0,1,13.0,0.000000,0.000000,0.000000,0.000000,NaN,NaN,100.312506,2.637995,3.114979,0.0,13,0.008719,2
3,lon_-66.884064_lat_1.226107,-66.884064,1.226107,609870.202163,<NA>,0,1,13.0,0.000000,0.000000,0.000000,0.000000,NaN,NaN,107.617527,1.806414,2.093173,0.0,13,0.009207,2
4,lon_-66.884064_lat_1.235088,-66.884064,1.235088,990398.533692,<NA>,0,1,13.0,68.751751,247.887964,893.772766,24.554197,NaN,NaN,102.933021,2.617245,2.938862,0.0,13,0.013381,2

## Balance summary by ever-treated status

This is a descriptive check, not a matching or weighting procedure. The standardized difference is computed as the treated-minus-never difference divided by the pooled standard deviation.

In [17]:
def balance_summary(df, group_col="ever_treated"):
    excluded = {"cell_id", "cell_lon", "cell_lat", "first_treat_year", "ever_treated", "never_treated"}
    numeric_cols = [c for c in df.select_dtypes(include=[np.number]).columns if c not in excluded]
    rows = []
    for col in numeric_cols:
        treated = pd.to_numeric(df.loc[df[group_col].eq(1), col], errors="coerce").dropna()
        control = pd.to_numeric(df.loc[df[group_col].eq(0), col], errors="coerce").dropna()
        t_mean = treated.mean() if len(treated) else np.nan
        c_mean = control.mean() if len(control) else np.nan
        t_sd = treated.std(ddof=1) if len(treated) > 1 else np.nan
        c_sd = control.std(ddof=1) if len(control) > 1 else np.nan
        pooled = np.sqrt((t_sd**2 + c_sd**2) / 2) if pd.notna(t_sd) and pd.notna(c_sd) else np.nan
        std_diff = (t_mean - c_mean) / pooled if pooled and pooled > 0 else np.nan
        rows.append({
            "covariate": col,
            "n_ever_treated": len(treated),
            "mean_ever_treated": t_mean,
            "sd_ever_treated": t_sd,
            "n_never_treated": len(control),
            "mean_never_treated": c_mean,
            "sd_never_treated": c_sd,
            "difference": t_mean - c_mean if pd.notna(t_mean) and pd.notna(c_mean) else np.nan,
            "standardized_difference": std_diff,
            "missing_share": df[col].isna().mean(),
        })
    return pd.DataFrame(rows)

balance = balance_summary(core_covariates)
balance.to_csv(BALANCE_SUMMARY_PATH, index=False)

print("Saved:", BALANCE_SUMMARY_PATH)
display(balance.sort_values("standardized_difference", key=lambda s: s.abs(), ascending=False).head(30))

Saved: C:\Users\cpedr\OneDrive - Hertie School\PhD\Paper 2\paper2\outputs\tables\04_covariate_balance_summary.csv

,covariate,n_ever_treated,mean_ever_treated,sd_ever_treated,n_never_treated,mean_never_treated,sd_never_treated,difference,standardized_difference,missing_share
12,dmsp_stable_lights_pre_years,226343,4.551901,5.633664,933675,13.000000,0.000000,-8.448099,-2.120718,0.000000
6,coca_pre_years,5402,16.141059,6.424306,122913,13.000000,0.000000,3.141059,0.691456,0.889385
8,elevation_m_mean,226343,840.198774,1095.517180,933675,490.213398,726.456372,349.985376,0.376536,0.000000
10,ruggedness_m_mean,226343,13.119515,14.874840,933675,8.915153,11.099521,4.204362,0.320365,0.000000
9,slope_deg_mean,226343,9.691761,10.039641,933675,6.862881,7.816265,2.828880,0.314428,0.000000
0,base_m2,226343,615019.730470,443670.305989,933675,512572.454268,434974.049357,102447.276203,0.233183,0.000000
2,forest_loss_pre_mean_m2,103488,925.582742,3164.230262,933675,1484.518010,4296.875131,-558.935268,-0.148129,0.105908
3,forest_loss_pre_sd_m2,103488,1904.524535,6272.055904,933675,2946.659920,8375.984415,-1042.135384,-0.140845,0.105908
4,forest_loss_pre_total_m2,103488,13527.236193,44774.483406,933675,19298.734131,55859.376706,-5771.497938,-0.114013,0.105908
7,coca_pre_mean_ha,5402,0.457826,0.983853,122913,0.538363,0.966922,-0.080537,-0.082566,0.889385
1,forest_loss_pre_years,103488,13.354234,7.077437,933675,13.000000,0.000000,0.354234,0.070783,0.105908
11,dmsp_stable_lights_pre_mean,103488,0.913555,4.314062,933675,1.060331,4.531065,-0.146777,-0.033178,0.105908
13,viirs_avg_rad_pre_mean,54710,0.265954,1.996380,933675,0.213082,2.256441,0.052871,0.024818,0.147957
14,viirs_avg_rad_pre_years,226343,2.029672,3.823745,933675,2.000000,0.000000,0.029672,0.010974,0.000000
5,forest_loss_pre_trend_m2_per_year,92101,-6.701551,779.656060,933675,-4.442336,777.731767,-2.259216,-0.002901,0.115724

## Notes on additional covariates

Good candidates for this notebook, in roughly decreasing priority:

1. `distance_to_roads_km`: use OpenStreetMap or an official Colombian road network outside GEE, then compute nearest-distance locally in a projected CRS. This is more transparent than relying on a stale or partial GEE road layer.
2. `distance_to_settlements_km` or `baseline_population_2000_sum`: population is already available through WorldPop; settlement distance can be added from GHSL built-up polygons or official settlement points.
3. `baseline_coca_presence_or_intensity`: likely needs licensed UNODC/SIMCI data or a formal request. If only department/municipality aggregates are available, keep it at that geography and label the unit clearly.
4. `pre_treatment_precipitation_mean` and `pre_treatment_temperature_mean`: useful if ecological productivity or accessibility varies strongly across cells; CHIRPS precipitation is straightforward in GEE.
5. `baseline_land_cover_shares`: MODIS MCD12Q1 classes can capture cropland, savanna, urban, and wetland shares around 2001.

Do not mix pre- and post-treatment vintages silently. If a variable is measured after some cells are treated, either exclude it from the main covariate set or label it as a sensitivity-only proxy.